### PR TITLE
Extract app identifiers

### PR DESCRIPTION
**Pull request by feralbob**
This pull request extracts a number of Apple Developer Account specific values from the pbxproj to a xcconfig file.

The extracted values include DEVELOPMENT_TEAM, APP_GROUPS and a base for the PRODUCT_BUNDLE_IDENTIFIER. The system includes a method to override them with a fallback to the current values for @EthanLipnik's account.

Ultimately this change makes it much easier for a contributor to setup OpenSesame in their own Apple Developer Account, including the ability to run app on device.

This change should be complete - but will require testing to make sure I've caught everything.

### CODE REVIEW

**Comment by feralbob** [comment]
I've just spotted another reference that I missed in the rebase - iCloud.com.ethanlipnik.OpenSesame in Persistence+Container.swift

**Comment by EthanLipnik** [comment]
This is some really great work! I'll be sure to test this branch and merge it soon!

**Comment by EthanLipnik** [comment]
After a merge I realized that macOS no longer compiles because for some reason it can't set the iCloud containers. Working on a fix

**Comment by EthanLipnik** [comment]
image
It seems that the only solution is to manually set the iCloud group. All the code should be working but for macOS it doesn't. Hopefully a new Xcode version will help. Opening an issue

**Comment by EthanLipnik** [comment]
Also may be from a temporary revert but your name won't show up in the contributions list for some reason even though your commits are in the git. If you'd like to be added to the list, make a new pull request for something new, could be something small @feralbob

**Comment by feralbob** [comment]
I'll take a look at why macOS isn't working correctly too

**Comment by EthanLipnik** [comment]
Fantastic! Thanks!

**Pull request merged**
